<?php

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;

class ThemeSeeder extends Seeder
{
    public function run(): void
    {
        $themes = [
            [
                'name' => 'Anime Sakura',
                'slug' => 'anime-sakura',
                'view_name' => 'themes.wedding.anime-sakura',
                'theme_category_id' => 1,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Zamrud Classic',
                'slug' => 'zamrud-classic',
                'view_name' => 'themes.wedding.zamrud-classic',
                'theme_category_id' => 1,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Soft Blue',
                'slug' => 'soft-blue',
                'view_name' => 'themes.wedding.soft-blue',
                'theme_category_id' => 1,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Classic Blue',
                'slug' => 'classic-blue',
                'view_name' => 'themes.wedding.classic-blue',
                'theme_category_id' => 1,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Classic White',
                'slug' => 'classic-white',
                'view_name' => 'themes.wedding.classic-white',
                'theme_category_id' => 1,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Dark Elegant',
                'slug' => 'dark-elegant',
                'view_name' => 'themes.wedding.dark-elegant',
                'theme_category_id' => 1,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Noir Elegance',
                'slug' => 'noir-elegance',
                'view_name' => 'themes.wedding.noir-elegance',
                'theme_category_id' => 1,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Minimalist Sage',
                'slug' => 'minimalist-sage',
                'view_name' => 'themes.wedding.minimalist-sage',
                'theme_category_id' => 1,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Elegant Gold',
                'slug' => 'elegant-gold',
                'view_name' => 'themes.wedding.elegant-gold',
                'theme_category_id' => 1,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Kids',
                'slug' => 'kids',
                'view_name' => 'themes.birthday.kids',
                'theme_category_id' => 2,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Modern',
                'slug' => 'modern',
                'view_name' => 'themes.birthday.Modern',
                'theme_category_id' => 2,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Elektrik Carnival',
                'slug' => 'elektrik-carnival',
                'view_name' => 'themes.birthday.elektrik-carnival',
                'theme_category_id' => 2,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Golden Milestone',
                'slug' => 'golden-milestone',
                'view_name' => 'themes.birthday.golden-milestone',
                'theme_category_id' => 2,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Fun Energik',
                'slug' => 'fun-energik',
                'view_name' => 'themes.birthday.fun-energik',
                'theme_category_id' => 2,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Night Party',
                'slug' => 'night-party',
                'view_name' => 'themes.birthday.night-party',
                'theme_category_id' => 2,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Pastel Floral',
                'slug' => 'pastel-floral-bday',
                'view_name' => 'themes.birthday.pastel-floral-bday',
                'theme_category_id' => 2,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Sweet 17',
                'slug' => 'sweet17',
                'view_name' => 'themes.birthday.sweet17',
                'theme_category_id' => 2,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Royal Tasyakur',
                'slug' => 'royal-tasyakur',
                'view_name' => 'themes.aqiqah.royal-tasyakur',
                'theme_category_id' => 3,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Islamic Theme',
                'slug' => 'islamic-theme',
                'view_name' => 'themes.aqiqah.islamic-theme',
                'theme_category_id' => 3,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Earthy Boho',
                'slug' => 'earthy-boho',
                'view_name' => 'themes.aqiqah.earthy-boho',
                'theme_category_id' => 3,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Dreamy Blue',
                'slug' => 'dreamy-blue',
                'view_name' => 'themes.aqiqah.dreamy-blue',
                'theme_category_id' => 3,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Sheep Theme',
                'slug' => 'sheep-theme',
                'view_name' => 'themes.aqiqah.sheep-theme',
                'theme_category_id' => 3,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Brave Hero',
                'slug' => 'brave-hero',
                'view_name' => 'themes.khitan.brave-hero',
                'theme_category_id' => 4,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Little Star',
                'slug' => 'little-star',
                'view_name' => 'themes.khitan.little-star',
                'theme_category_id' => 4,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Green Leaf',
                'slug' => 'green-leaf',
                'view_name' => 'themes.khitan.green-leaf',
                'theme_category_id' => 4,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Blue Ocean',
                'slug' => 'blue-ocean',
                'view_name' => 'themes.khitan.blue-ocean',
                'theme_category_id' => 4,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Moon Star',
                'slug' => 'moon-star',
                'view_name' => 'themes.khitan.moon-star',
                'theme_category_id' => 4,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Botanica Soft',
                'slug' => 'botanica-soft',
                'view_name' => 'themes.tunangan.botanica-soft',
                'theme_category_id' => 5,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Classic Monochrome',
                'slug' => 'classic-monochrome',
                'view_name' => 'themes.tunangan.classic-monochrome',
                'theme_category_id' => 5,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Blossom Romance',
                'slug' => 'blossom-romance',
                'view_name' => 'themes.tunangan.blossom-romance',
                'theme_category_id' => 5,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Rustic Journey',
                'slug' => 'rustic-journey',
                'view_name' => 'themes.tunangan.rustic-journey',
                'theme_category_id' => 5,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Vintage Academic',
                'slug' => 'vintage-academic',
                'view_name' => 'themes.wisuda.vintage-academic',
                'theme_category_id' => 6,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Diploma Prestige',
                'slug' => 'diploma-prestige',
                'view_name' => 'themes.wisuda.diploma-prestige',
                'theme_category_id' => 6,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Elegant Navy',
                'slug' => 'elegant-navy',
                'view_name' => 'themes.wisuda.elegant-navy',
                'theme_category_id' => 6,
                'price' => 50000,
                'is_premium' => true,
            ],
            [
                'name' => 'Modern Graduate',
                'slug' => 'modern-graduate',
                'view_name' => 'themes.wisuda.modern-graduate',
                'theme_category_id' => 6,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Great Vibes',
                'slug' => 'great-vibes',
                'view_name' => 'themes.wisuda.great-vibes',
                'theme_category_id' => 6,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Emerald Mosque',
                'slug' => 'syukuran-emerald-mosque',
                'view_name' => 'themes.syukuran.syukuran-emerald-mosque',
                'theme_category_id' => 7,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Minimalist Elegant',
                'slug' => 'minimalist-elegant',
                'view_name' => 'themes.syukuran.minimalist-elegant',
                'theme_category_id' => 7,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Sahara Night',
                'slug' => 'syukuran-sahara-night',
                'view_name' => 'themes.syukuran.syukuran-sahara-night',
                'theme_category_id' => 7,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Islamic Arabesque',
                'slug' => 'islamic-arabesque',
                'view_name' => 'themes.syukuran.islamic-arabesque',
                'theme_category_id' => 7,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Gold Arabesque',
                'slug' => 'syukuran-gold-arabesque',
                'view_name' => 'themes.syukuran.syukuran-gold-arabesque',
                'theme_category_id' => 7,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Chalk Memories',
                'slug' => 'chalk-memories',
                'view_name' => 'themes.reuni.chalk-memories',
                'theme_category_id' => 8,
                'price' => 0,
                'is_premium' => false,
            ],
            [
                'name' => 'Retro Fest',
                'slug' => 'retro-fest',
                'view_name' => 'themes.reuni.retro-fest',
                'theme_category_id' => 8,
                'price' => 0,
                'is_premium' => false,
            ],
        ];

        foreach ($themes as $themeData) {
            Theme::updateOrCreate(
                ['slug' => $themeData['slug']],
                $themeData
            );
        }
    }
}
